export const GUIDE_EN = {
  lang: 'en',
  dir: 'ltr',
  pageTitle: 'User Manual',
  downloadBtn: 'Download PDF',
  pdfTitle: 'Complete User Manual',
  welcomePrefix: 'Welcome,',
  rights: 'All rights reserved',
  appDesc: 'A smart solar energy management platform — it collects your energy, manages it intelligently, and sells it at the right moment to maximize your profit.',

  prereqTitle: '📋 Prerequisites — Before You Start',
  prereqs: [
    {
      icon: '🏢',
      title: 'Apply for Time-of-Use (ToU) Tariff',
      body: 'Contact the Israel Electric Corporation and request a switch to dynamic pricing (ToU). Submit a digital request via:',
      link: { label: 'IEC Customer Service Form', url: 'https://www.iec.co.il/content/lobbies/pniot' },
      note: 'After switching, your bill will show off-peak (low price) and peak (high price) hours — the foundation of the entire strategy.',
    },
    {
      icon: '☀️',
      title: 'Connect SolarEdge API',
      body: 'Log in to the SolarEdge portal > Account > API Access > Create an API Key. Enter it in VPP Settings along with your Site ID(s).',
      note: 'This allows the app to see in real-time how much electricity your panels produce and what the physical battery status is.',
    },
    {
      icon: '⚡',
      title: 'Noga Energy API Credentials',
      body: 'To obtain a Noga ISO Client ID + Secret, contact the VPP Solar Club team. This provides access to real-time electricity prices.',
      note: 'Without this connection the app runs in Simulation Mode — everything works, but with simulated price data.',
    },
    {
      icon: '📱',
      title: 'Set Up Payment Method',
      body: 'Go to Profile > Payment Management and add a credit card. Required to receive payments for energy sold to the grid.',
      note: 'You can start in simulation mode without payment — but real income requires a connection.',
    },
  ],

  stepsTitle: '🚀 Step-by-Step Usage Guide',
  steps: [
    { num: '01', icon: '👤', title: 'Login & Profile', color: '#10b981',
      desc: 'Log in with your email or phone. In the Profile tab, fill in your household details — solar system size, battery type and address.',
      why: 'Why? The app calculates recommendations based on your system size.',
      link: { label: 'Go to My Profile', path: '/Profile' } },
    { num: '02', icon: '🏠', title: 'Main Dashboard — VPP Home', color: '#3b82f6',
      desc: 'In the "Home" tab: real-time energy flow (panels → home → grid), battery status, current electricity price and profitability index.',
      why: 'Why? Check it every morning to plan your day.',
      link: { label: 'Go to Dashboard', path: '/Dashboard' } },
    { num: '03', icon: '🔋', title: 'Smart Battery Charging', color: '#10b981',
      desc: 'Tap "Charge Battery". Choose an energy source and a target charge percentage. Tap "Apply AI Recommendation" for an automatic strategy.',
      why: 'Why? Charge between 10:00–16:00 when the sun is at its peak and grid prices are low.',
      link: { label: 'Go to Charge Battery', path: '/charge-battery' } },
    { num: '04', icon: '📤', title: 'Sell to Grid', color: '#f59e0b',
      desc: 'Tap "Sell to Grid". Choose how many kWh and when — immediately or scheduled. The app recommends peak hours (20:00–23:00).',
      why: 'Why? Electricity prices during peak hours are 3–5× higher — this is where you earn.',
      link: { label: 'Go to Sell to Grid', path: '/sell-to-grid' } },
    { num: '05', icon: '⏰', title: 'Automatic Schedules', color: '#8b5cf6',
      desc: 'In the "Schedule" tab, set recurring rules: "Every day at 11:00 — charge to 90%", "Every day at 21:00 — sell 10 kWh".',
      why: 'Why? Automation ensures you never miss peak hours.',
      link: { label: 'Go to Schedules', path: '/Schedule' } },
    { num: '06', icon: '📊', title: 'Track Savings & Revenue', color: '#10b981',
      desc: 'In the "Savings" tab, track monthly revenue, electricity bill savings and farm performance. Download a monthly PDF report.',
      why: 'Why? Weekly monitoring lets you refine your strategy and grow profits.',
      link: { label: 'Go to Savings', path: '/Savings' } },
    { num: '07', icon: '🖥️', title: 'VPP Command Center', color: '#06b6d4',
      desc: 'More > VPP Command Center. Real-time electricity prices, 24-hour price chart and status of all batteries in the fleet.',
      why: 'Why? This data helps you decide when to charge and when to sell.',
      link: { label: 'Go to VPP Command Center', path: '/vpp-command-center' } },
    { num: '08', icon: '⚙️', title: 'Advanced Settings', color: '#f59e0b',
      desc: 'More > VPP Settings. Enter API Keys, toggle Simulation/Live Mode and check connection status.',
      why: 'Why? Switching to Live Mode is essential to trade with real money.',
      link: { label: 'Go to VPP Settings', path: '/vpp-settings' } },
    { num: '09', icon: '🌞', title: 'Solar Club — Community', color: '#f59e0b',
      desc: 'In the "SolarClub" tab: join virtual solar farms, track community performance and purchase additional virtual panels.',
      why: 'Why? Virtual panels generate passive income even without a personal rooftop.',
      link: { label: 'Go to VPP Solar Club', path: '/vpp-club-dashboard' } },
    { num: '10', icon: '🤝', title: 'Refer Friends', color: '#eab308',
      desc: 'More > Refer a Friend. 1 friend — free month. 3 friends — 3 months + panel cleaning. 5 friends — Founder Circle VIP.',
      why: 'Why? Every friend increases collective fleet power and improves selling prices.',
      link: { label: 'Go to Referrals', path: '/referral' } },
  ],

  tipsTitle: '💡 Tips for Optimal Use',
  tips: [
    'Check the dashboard every morning — 30 seconds is enough to decide for the day.',
    'Schedule sales for 20:00–23:00 on weekdays — IEC peak hours.',
    'Charge battery 10:00–16:00 when panels produce maximum output.',
    'Enable ECO Profit Mode for full automation with zero intervention.',
    'Watch alerts — the app notifies you about production anomalies.',
    'In winter, sunshine is weaker — rely more on community farms.',
  ],
};