import React, { useCallback } from 'react';
import { Download } from 'lucide-react';
import { toast } from 'sonner';

/**
 * Generates and downloads a styled PDF report using jsPDF.
 * No external chart rendering — draws everything natively.
 */
export default function ExportReportPDF({ analysis, extracted, rev, recs, risks, roiSummary, period, profileLabel, isHe }) {
  const handleExport = useCallback(async () => {
    const toastId = toast.loading(isHe ? 'מייצר דוח PDF...' : 'Generating PDF report...');
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

      const W = 210;
      const MARGIN = 14;
      const COL = W - MARGIN * 2;
      let y = 0;

      // ── helpers ──────────────────────────────────────────────────────────
      const hex2rgb = (hex) => {
        const r = parseInt(hex.slice(1, 3), 16);
        const g = parseInt(hex.slice(3, 5), 16);
        const b = parseInt(hex.slice(5, 7), 16);
        return [r, g, b];
      };

      const setColor = (hex) => { const [r, g, b] = hex2rgb(hex); doc.setTextColor(r, g, b); };
      const setFill  = (hex) => { const [r, g, b] = hex2rgb(hex); doc.setFillColor(r, g, b); };
      const setDraw  = (hex) => { const [r, g, b] = hex2rgb(hex); doc.setDrawColor(r, g, b); };

      const checkPage = (needed = 10) => {
        if (y + needed > 277) { doc.addPage(); y = 18; }
      };

      const sectionTitle = (text, color = '#7C3AED') => {
        checkPage(12);
        setFill(color + '22');
        setDraw(color);
        doc.setLineWidth(0.3);
        doc.roundedRect(MARGIN, y, COL, 8, 2, 2, 'FD');
        setColor(color);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text(text, MARGIN + 3, y + 5.5);
        y += 11;
      };

      const row = (label, value, labelColor = '#64748b', valueColor = '#1e293b') => {
        checkPage(7);
        setColor(labelColor);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.text(label, MARGIN + 2, y);
        setColor(valueColor);
        doc.setFont('helvetica', 'bold');
        doc.text(String(value ?? '—'), W - MARGIN - 2, y, { align: 'right' });
        // divider
        setDraw('#e2e8f0');
        doc.setLineWidth(0.1);
        doc.line(MARGIN, y + 1.5, W - MARGIN, y + 1.5);
        y += 6.5;
      };

      const miniBar = (value, max, color = '#7C3AED') => {
        const barW = Math.max(2, (value / max) * (COL - 30));
        setFill('#e2e8f0');
        doc.roundedRect(MARGIN + 28, y - 3.5, COL - 30, 3, 1, 1, 'F');
        setFill(color);
        doc.roundedRect(MARGIN + 28, y - 3.5, barW, 3, 1, 1, 'F');
      };

      // ── COVER ─────────────────────────────────────────────────────────────
      // dark header band
      setFill('#0A0F1E');
      doc.rect(0, 0, W, 52, 'F');

      // accent stripe
      setFill('#7C3AED');
      doc.rect(0, 48, W, 4, 'F');

      setColor('#ffffff');
      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.text(isHe ? 'דוח ארביטראז׳ אנרגיה' : 'Energy Arbitrage Report', W / 2, 22, { align: 'center' });

      setColor('#a78bfa');
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`${profileLabel.emoji}  ${isHe ? profileLabel.he : profileLabel.en}  ·  ${period.detected_period || '—'}`, W / 2, 32, { align: 'center' });

      setColor('#64748b');
      doc.setFontSize(8);
      doc.text(`${isHe ? 'הופק ע"י VPP AI' : 'Generated by VPP AI'}  ·  ${new Date().toLocaleDateString('he-IL')}`, W / 2, 41, { align: 'center' });

      y = 60;

      // ── AI SUMMARY ────────────────────────────────────────────────────────
      if (analysis.summary) {
        sectionTitle(`🤖  ${isHe ? 'סיכום AI' : 'AI Summary'}`, '#7C3AED');
        setFill('#f5f3ff');
        setDraw('#ddd6fe');
        doc.setLineWidth(0.2);
        const lines = doc.splitTextToSize(analysis.summary, COL - 6);
        const boxH = lines.length * 4.8 + 4;
        checkPage(boxH + 4);
        doc.roundedRect(MARGIN, y, COL, boxH, 2, 2, 'FD');
        setColor('#4c1d95');
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.text(lines, MARGIN + 3, y + 4.5);
        y += boxH + 6;
      }

      // ── MISSING ROI HIGHLIGHT ─────────────────────────────────────────────
      const gap = rev.missing_roi_ils || 0;
      if (gap > 0) {
        checkPage(22);
        setFill('#fffbeb');
        setDraw('#f59e0b');
        doc.setLineWidth(0.4);
        doc.roundedRect(MARGIN, y, COL, 20, 3, 3, 'FD');

        setColor('#92400e');
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.text(isHe ? 'פוטנציאל ROI שאבד' : 'Missing ROI Potential', MARGIN + 4, y + 5);

        setColor('#b45309');
        doc.setFontSize(20);
        doc.setFont('helvetica', 'bold');
        doc.text(`+₪${Number(gap).toLocaleString()}`, MARGIN + 4, y + 15);

        setColor('#78350f');
        doc.setFontSize(7.5);
        doc.setFont('helvetica', 'normal');
        doc.text(isHe ? 'ניתן לשחזר עם VPP AI' : 'Recoverable with VPP AI', W - MARGIN - 4, y + 15, { align: 'right' });
        y += 25;
      }

      // ── REVENUE ANALYSIS ──────────────────────────────────────────────────
      if (rev.actual_revenue_ils > 0) {
        sectionTitle(`💰  ${isHe ? 'ניתוח הכנסות' : 'Revenue Analysis'}`, '#059669');
        row(isHe ? 'הכנסה בפועל' : 'Actual Revenue',      `₪${Number(rev.actual_revenue_ils).toLocaleString()}`,               '#64748b', '#dc2626');
        row(isHe ? 'מותאם VPP AI' : 'VPP AI Optimized',   `₪${Number(rev.optimized_revenue_ils || 0).toLocaleString()}`,       '#64748b', '#059669');
        if (rev.monthly_avg_ils)          row(isHe ? 'ממוצע חודשי' : 'Monthly Avg',      `₪${Number(rev.monthly_avg_ils).toLocaleString()}`,          '#64748b', '#2563eb');
        if (rev.quarterly_projection_ils) row(isHe ? 'תחזית רבעונית' : 'Quarterly Proj.',`₪${Number(rev.quarterly_projection_ils).toLocaleString()}`, '#64748b', '#7c3aed');
        if (rev.annual_projection_ils)    row(isHe ? 'תחזית שנתית' : 'Annual Proj.',      `₪${Number(rev.annual_projection_ils).toLocaleString()}`,    '#64748b', '#d97706');
        y += 3;
      }

      // ── EXTRACTED DATA ────────────────────────────────────────────────────
      const hasExtracted = extracted.total_kwh || extracted.tariff_per_kwh || extracted.total_amount_ils || extracted.provider;
      if (hasExtracted) {
        sectionTitle(`📋  ${isHe ? 'נתונים שחולצו מהמסמך' : 'Extracted Document Data'}`, '#0369a1');
        if (extracted.billing_period)    row(isHe ? 'תקופת חיוב' : 'Billing Period',   extracted.billing_period,                             '#64748b', '#1e293b');
        if (extracted.provider)          row(isHe ? 'ספק' : 'Provider',                 extracted.provider,                                   '#64748b', '#1e293b');
        if (extracted.meter_id)          row('Meter ID',                                  extracted.meter_id,                                   '#64748b', '#1e293b');
        if (extracted.total_kwh)         row(isHe ? 'סה"כ צריכה' : 'Total Usage',       `${extracted.total_kwh} kWh`,                         '#64748b', '#d97706');
        if (extracted.tariff_per_kwh)    row(isHe ? 'תעריף ממוצע' : 'Avg Tariff',       `₪${extracted.tariff_per_kwh}/kWh`,                   '#64748b', '#059669');
        if (extracted.total_amount_ils)  row(isHe ? 'סה"כ חשבון' : 'Total Billed',      `₪${Number(extracted.total_amount_ils).toLocaleString()}`, '#64748b', '#dc2626');
        if (extracted.system_capacity_kw)row(isHe ? 'הספק מערכת' : 'System Capacity',  `${extracted.system_capacity_kw} kWp`,                '#64748b', '#7c3aed');
        if (extracted.annual_yield_kwh)  row(isHe ? 'ייצור שנתי' : 'Annual Yield',      `${extracted.annual_yield_kwh} kWh`,                  '#64748b', '#059669');
        if (extracted.co2_saved_kg > 0)  row('🌱 CO₂',                                   `${Number(extracted.co2_saved_kg).toLocaleString()} kg`, '#64748b', '#16a34a');
        y += 3;
      }

      // ── ROI SUMMARY ───────────────────────────────────────────────────────
      const hasRoi = roiSummary.irr_percent || roiSummary.payback_years || roiSummary.npv_ils;
      if (hasRoi) {
        sectionTitle(`📈  ${isHe ? 'סיכום ROI / השקעה' : 'Investment Summary'}`, '#d97706');
        if (roiSummary.irr_percent)        row('IRR',                                         `${roiSummary.irr_percent}%`,                              '#64748b', '#d97706');
        if (roiSummary.payback_years)      row(isHe ? 'זמן החזר השקעה' : 'Payback Period',    `${roiSummary.payback_years} ${isHe ? 'שנים' : 'yrs'}`,   '#64748b', '#d97706');
        if (roiSummary.npv_ils)            row('NPV',                                          `₪${Number(roiSummary.npv_ils).toLocaleString()}`,          '#64748b', '#059669');
        if (roiSummary.co2_saved_annual_kg)row('CO₂/yr',                                      `${Number(roiSummary.co2_saved_annual_kg).toLocaleString()} kg`, '#64748b', '#16a34a');
        y += 3;
      }

      // ── ARBITRAGE BAR CHART (drawn natively) ──────────────────────────────
      const DEFAULT_HOURLY = [
        { hour: '06', loss_kwh: 0.2 }, { hour: '08', loss_kwh: 0.5 },
        { hour: '10', loss_kwh: 0.8 }, { hour: '12', loss_kwh: 0.6 },
        { hour: '14', loss_kwh: 0.4 }, { hour: '17', loss_kwh: 1.2 },
        { hour: '18', loss_kwh: 3.1 }, { hour: '19', loss_kwh: 3.8 },
        { hour: '20', loss_kwh: 2.9 },
      ];
      const hourlyData = (Array.isArray(analysis.hourly_loss_profile) && analysis.hourly_loss_profile.length > 0)
        ? analysis.hourly_loss_profile : DEFAULT_HOURLY;

      checkPage(52);
      sectionTitle(`⚡  ${isHe ? 'אובדן ארביטראז׳ לפי שעה' : 'Hourly Arbitrage Loss'}`, '#7C3AED');

      const chartH = 30;
      const chartW = COL;
      const maxLoss = Math.max(...hourlyData.map(d => d.loss_kwh), 1);
      const barW2 = chartW / hourlyData.length * 0.6;
      const gap2  = chartW / hourlyData.length;

      // bg
      setFill('#f8fafc');
      setDraw('#e2e8f0');
      doc.setLineWidth(0.2);
      doc.roundedRect(MARGIN, y, COL, chartH + 8, 2, 2, 'FD');

      hourlyData.forEach((d, i) => {
        const barH = (d.loss_kwh / maxLoss) * chartH * 0.85;
        const bx = MARGIN + i * gap2 + (gap2 - barW2) / 2;
        const by = y + chartH - barH + 2;
        const color = d.loss_kwh > 3 ? '#ef4444' : d.loss_kwh > 1.5 ? '#f59e0b' : '#10b981';
        setFill(color);
        doc.roundedRect(bx, by, barW2, barH, 0.5, 0.5, 'F');

        // hour label
        setColor('#94a3b8');
        doc.setFontSize(5.5);
        doc.setFont('helvetica', 'normal');
        doc.text(d.hour, bx + barW2 / 2, y + chartH + 6, { align: 'center' });
      });
      y += chartH + 14;

      // legend
      [['#10b981', isHe ? 'נמוך' : 'Low'], ['#f59e0b', isHe ? 'בינוני' : 'Medium'], ['#ef4444', isHe ? 'גבוה' : 'High']].forEach(([c, l], i) => {
        setFill(c);
        doc.roundedRect(MARGIN + i * 28, y, 4, 3, 0.5, 0.5, 'F');
        setColor('#64748b');
        doc.setFontSize(6.5);
        doc.text(l, MARGIN + i * 28 + 5.5, y + 2.5);
      });
      y += 7;

      // ── RECOMMENDATIONS ───────────────────────────────────────────────────
      if (recs.length > 0) {
        checkPage(14);
        sectionTitle(`🎯  ${isHe ? 'המלצות AI' : 'AI Recommendations'}`, '#7C3AED');

        const priorityColor = { high: '#dc2626', medium: '#d97706', low: '#059669' };
        const priorityLabel = { high: isHe ? 'גבוהה' : 'High', medium: isHe ? 'בינונית' : 'Med', low: isHe ? 'נמוכה' : 'Low' };

        recs.forEach((r, i) => {
          const pc = priorityColor[r.priority] || '#7c3aed';
          const pl = priorityLabel[r.priority] || r.priority;
          const titleLines = doc.splitTextToSize(r.title_he || r.title_en || '', COL - 30);
          const descLines  = doc.splitTextToSize(r.desc_he  || r.desc_en  || '', COL - 10);
          const boxH = titleLines.length * 4.5 + descLines.length * 3.8 + 12;

          checkPage(boxH + 4);

          setFill(pc + '11');
          setDraw(pc + '55');
          doc.setLineWidth(0.25);
          doc.roundedRect(MARGIN, y, COL, boxH, 2, 2, 'FD');

          // priority dot + label
          setFill(pc);
          doc.circle(MARGIN + 4, y + 5, 1.2, 'F');
          setColor(pc);
          doc.setFontSize(7);
          doc.setFont('helvetica', 'bold');
          doc.text(pl, MARGIN + 7, y + 5.5);

          // gain
          if (r.estimated_gain_ils > 0) {
            setColor('#059669');
            doc.setFont('helvetica', 'bold');
            doc.text(`+₪${Number(r.estimated_gain_ils).toLocaleString()}`, W - MARGIN - 3, y + 5.5, { align: 'right' });
          }

          // title
          setColor('#1e293b');
          doc.setFontSize(8.5);
          doc.setFont('helvetica', 'bold');
          doc.text(titleLines, MARGIN + 3, y + 10);

          // desc
          setColor('#475569');
          doc.setFontSize(7.2);
          doc.setFont('helvetica', 'normal');
          doc.text(descLines, MARGIN + 3, y + 10 + titleLines.length * 4.5);

          y += boxH + 3;
        });
      }

      // ── RISK FLAGS ────────────────────────────────────────────────────────
      if (risks.length > 0) {
        checkPage(10 + risks.length * 6);
        sectionTitle(`⚠️  ${isHe ? 'ממצאי סיכון' : 'Risk Flags'}`, '#dc2626');
        risks.forEach(flag => {
          checkPage(7);
          setColor('#dc2626');
          doc.setFontSize(7.5);
          doc.setFont('helvetica', 'normal');
          const lines = doc.splitTextToSize(`• ${flag}`, COL - 4);
          doc.text(lines, MARGIN + 2, y);
          y += lines.length * 4.5 + 1;
        });
        y += 3;
      }

      // ── FOOTER ────────────────────────────────────────────────────────────
      const pageCount = doc.internal.getNumberOfPages();
      for (let p = 1; p <= pageCount; p++) {
        doc.setPage(p);
        setFill('#0A0F1E');
        doc.rect(0, 285, W, 12, 'F');
        setColor('#a78bfa');
        doc.setFontSize(6.5);
        doc.setFont('helvetica', 'normal');
        doc.text(`VPP AI  ·  ${isHe ? 'דוח ארביטראז׳ אנרגיה' : 'Energy Arbitrage Report'}  ·  ${new Date().toLocaleDateString('he-IL')}`, MARGIN, 290.5);
        setColor('#475569');
        doc.text(`${p} / ${pageCount}`, W - MARGIN, 290.5, { align: 'right' });
      }

      doc.save(`VPP_Arbitrage_Report_${new Date().toISOString().split('T')[0]}.pdf`);
      toast.dismiss(toastId);
      toast.success(isHe ? '✅ הדוח הורד בהצלחה!' : '✅ Report downloaded!');
    } catch (err) {
      toast.dismiss(toastId);
      toast.error(isHe ? `שגיאה: ${err.message}` : `Error: ${err.message}`);
    }
  }, [analysis, extracted, rev, recs, risks, roiSummary, period, profileLabel, isHe]);

  return (
    <button
      onClick={handleExport}
      className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-black transition-all active:scale-95"
      style={{
        background: 'linear-gradient(135deg,rgba(16,185,129,0.2),rgba(5,150,105,0.15))',
        border: '1px solid rgba(16,185,129,0.4)',
        color: '#10b981',
      }}
    >
      <Download className="w-3.5 h-3.5" />
      {isHe ? 'ייצוא PDF' : 'Export PDF'}
    </button>
  );
}